module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ['module-resolver',
      {
        root: ['.'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          '@root': './',
          '@': ['./examples', './src', './debug', './generated'],
          '@components': [
            './examples/components',
            './src/components',
            './debug/components',
            './generated/components',
            './internal/components',
          ],
          '@screens': [
            './examples/screens',
            './src/screens',
            './debug/screens',
            './generated/screens',
            './internal/screens',
          ],
          '@stores': [
            './examples/stores',
            './src/stores',
            './debug/stores',
            './generated/stores',
            './internal/stores',
          ],
          '@theme': [
            './examples/theme',
            './src/theme',
            './debug/theme',
            './generated/theme',
            './internal/theme',
          ],
          '@constants': [
            './examples/constants',
            './src/constants',
            './debug/constants',
            './generated/constants',
            './internal/constants',
          ],
          '@navigation': [
            './examples/navigation',
            './src/navigation',
            './debug/navigation',
            './generated/navigation',
            './internal/navigation',
          ],
          '@schemas': [
            './examples/schemas',
            './src/schemas',
            './debug/schemas',
            './generated/schemas',
            './internal/schemas',
          ],
          '@localization': [
            './examples/localization',
            './src/localization',
            './debug/localization',
            './generated/localization',
            './internal/localization',
          ],
        },
      },
    ],
    '@babel/plugin-proposal-export-default-from',
  ],
}
